FOLD_LISTS = ['StationList.Station.Address.PostalAddress.A_5LineAddress.Line',
             'StationList.Station.InformationSystems.CIS',
             'StationList.Station.Accessibility.NearestStationsWithMoreFacilities.CrsCode',
             'StationList.Station.Interchange.CarPark.ContactDetails.PostalAddress.Line',
             'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability', 'StationList.Station',
             'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability',
             'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability',
             'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability',
             'StationList.Station.Interchange.CarPark',
             'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability',
             'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability',
             'StationList.Station.InformationSystems.InformationAvailableFromStaff',
             'StationList.Station.Fares.PenaltyFares.TrainOperator',
             'StationList.Station.Interchange.CycleStorage.Type',
             'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.OpenPeriod',
             'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability',
             'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
             'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability',
             'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
             'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability',
             'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
             'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
             'StationList.Station.TrainOperatingCompanies.TocRef']
EXCLUDE_DATA = ['StationList', 'StationList.Station', 'StationList.Station.ChangeHistory',
               'StationList.Station.AlternativeIdentifiers', 'StationList.Station.Address',
               'StationList.Station.Address.PostalAddress', 'StationList.Station.Address.PostalAddress.A_5LineAddress',
               'StationList.Station.Staffing', 'StationList.Station.Staffing.ClosedCircuitTelevision',
               'StationList.Station.InformationSystems',
               'StationList.Station.InformationSystems.InformationServicesOpen',
               'StationList.Station.InformationSystems.InformationServicesOpen.Annotation',
               'StationList.Station.InformationSystems.CustomerHelpPoints', 'StationList.Station.Fares',
               'StationList.Station.Fares.TicketOffice', 'StationList.Station.Fares.TicketMachine',
               'StationList.Station.Fares.SmartcardComments', 'StationList.Station.Fares.PenaltyFares',
               'StationList.Station.PassengerServices', 'StationList.Station.PassengerServices.CustomerService',
               'StationList.Station.PassengerServices.CustomerService.Annotation',
               'StationList.Station.PassengerServices.LeftLuggage',
               'StationList.Station.PassengerServices.LeftLuggage.ContactDetails',
               'StationList.Station.PassengerServices.LostProperty',
               'StationList.Station.PassengerServices.LostProperty.ContactDetails',
               'StationList.Station.PassengerServices.LostProperty.ContactDetails.PrimaryTelephoneNumber',
               'StationList.Station.StationFacilities', 'StationList.Station.StationFacilities.FirstClassLounge',
               'StationList.Station.StationFacilities.SeatedArea', 'StationList.Station.StationFacilities.WaitingRoom',
               'StationList.Station.StationFacilities.Trolleys', 'StationList.Station.StationFacilities.StationBuffet',
               'StationList.Station.StationFacilities.Toilets', 'StationList.Station.StationFacilities.BabyChange',
               'StationList.Station.StationFacilities.Showers', 'StationList.Station.StationFacilities.Telephones',
               'StationList.Station.StationFacilities.WiFi', 'StationList.Station.StationFacilities.WiFi.Annotation',
               'StationList.Station.StationFacilities.WebKiosk', 'StationList.Station.StationFacilities.PostBox',
               'StationList.Station.StationFacilities.TouristInformation',
               'StationList.Station.StationFacilities.AtmMachine',
               'StationList.Station.StationFacilities.BureauDeChange', 'StationList.Station.StationFacilities.Shops',
               'StationList.Station.Accessibility', 'StationList.Station.Accessibility.Helpline',
               'StationList.Station.Accessibility.Helpline.ContactDetails',
               'StationList.Station.Accessibility.Helpline.ContactDetails.Annotation',
               'StationList.Station.Accessibility.Helpline.Open',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.Accessibility.StaffHelpAvailable',
               'StationList.Station.Accessibility.StaffHelpAvailable.Annotation',
               'StationList.Station.Accessibility.AccessibleTicketMachines',
               'StationList.Station.Accessibility.AccessibleTicketMachines.Annotation',
               'StationList.Station.Accessibility.HeightAdjustedTicketOfficeCounter',
               'StationList.Station.Accessibility.RampForTrainAccess',
               'StationList.Station.Accessibility.NearestStationsWithMoreFacilities',
               'StationList.Station.Accessibility.NationalKeyToilets',
               'StationList.Station.Accessibility.StepFreeAccess',
               'StationList.Station.Accessibility.StepFreeAccess.Annotation',
               'StationList.Station.Accessibility.ImpairedMobilitySetDown',
               'StationList.Station.Accessibility.WheelchairsAvailable', 'StationList.Station.Interchange',
               'StationList.Station.Interchange.CycleStorage', 'StationList.Station.Interchange.CarPark',
               'StationList.Station.Interchange.CarPark.ContactDetails',
               'StationList.Station.Interchange.CarPark.ContactDetails.PostalAddress',
               'StationList.Station.Interchange.CarPark.Open',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.Interchange.CarPark.Charges',
               'StationList.Station.Interchange.RailReplacementServices',
               'StationList.Station.Interchange.RailReplacementServices.Annotation',
               'StationList.Station.Interchange.TaxiRank', 'StationList.Station.Interchange.TaxiRank.Annotation',
               'StationList.Station.StationAlerts', 'StationList.Station.TrainOperatingCompanies',
               'StationList.Station.Fares.PrepurchaseCollection',
               'StationList.Station.Interchange.CarPark.ContactDetails.PrimaryTelephoneNumber',
               'StationList.Station.Fares.TicketOffice.Open', 'StationList.Station.Fares.TicketOffice.Open.Annotation',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.Fares.SmartcardTopup',
               'StationList.Station.Interchange.CarPark.ContactDetails.Annotation',
               'StationList.Station.Interchange.OnwardTravel',
               'StationList.Station.Interchange.OnwardTravel.Annotation',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.Interchange.CycleStorage.Location',
               'StationList.Station.Fares.TicketOffice.Location',
               'StationList.Station.StationFacilities.WaitingRoom.Open',
               'StationList.Station.StationFacilities.WaitingRoom.Open.Annotation',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.StationFacilities.StationBuffet.Annotation',
               'StationList.Station.StationFacilities.Toilets.Location',
               'StationList.Station.Accessibility.Helpline.Annotation',
               'StationList.Station.Accessibility.AccessibleTaxis',
               'StationList.Station.Accessibility.AccessibleTaxis.Annotation',
               'StationList.Station.Accessibility.AccessiblePublicTelephones',
               'StationList.Station.Accessibility.AccessiblePublicTelephones.Annotation',
               'StationList.Station.Accessibility.ImpairedMobilitySetDown.Annotation',
               'StationList.Station.Accessibility.NationalKeyToilets.Location',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.InformationSystems.CustomerHelpPoints.Annotation',
               'StationList.Station.StationFacilities.PostBox.Location',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.StationFacilities.Shops.Annotation', 'StationList.Station.Interchange.CycleHire',
               'StationList.Station.Interchange.CycleHire.Annotation', 'StationList.Station.Accessibility.TicketGates',
               'StationList.Station.Interchange.CycleStorage.Annotation',
               'StationList.Station.StationFacilities.FirstClassLounge.Annotation',
               'StationList.Station.StationFacilities.FirstClassLounge.Open',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.StationFacilities.WaitingRoom.Location',
               'StationList.Station.StationFacilities.AtmMachine.Location',
               'StationList.Station.Accessibility.TicketGates.Annotation', 'StationList.Station.Interchange.Airport',
               'StationList.Station.Interchange.Airport.Annotation',
               'StationList.Station.Accessibility.NearestStationsWithMoreFacilities.Annotation',
               'StationList.Station.Interchange.Port', 'StationList.Station.Interchange.Port.Annotation',
               'StationList.Station.Accessibility.HeightAdjustedTicketOfficeCounter.Annotation',
               'StationList.Station.Fares.OystercardTopup', 'StationList.Station.Fares.Travelcard',
               'StationList.Station.PassengerServices.LostProperty.Open',
               'StationList.Station.PassengerServices.LostProperty.Open.Annotation',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.Interchange.MetroServices',
               'StationList.Station.Interchange.MetroServices.Annotation', 'StationList.Station.Fares.OysterComments',
               'StationList.Station.StationFacilities.BabyChange.Location',
               'StationList.Station.StationFacilities.SeatedArea.Annotation',
               'StationList.Station.StationFacilities.WebKiosk.Open',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.OpeningHours',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod',
               'StationList.Station.StationFacilities.TouristInformation.Location',
               'StationList.Station.Interchange.CarPark.Annotation', 'StationList.Station.Interchange.CarHire',
               'StationList.Station.Interchange.CarHire.Annotation',
               'StationList.Station.Interchange.CarPark.ContactDetails.AlternatePublicTelephoneNumbers',
               'StationList.Station.Interchange.CarPark.ContactDetails.AlternatePublicTelephoneNumbers.TelephoneNumber',
               'StationList.Station.Accessibility.Helpline.Open.Annotation',
               'StationList.Station.PassengerServices.LeftLuggage.ContactDetails.PrimaryTelephoneNumber',
               'StationList.Station.Interchange.CarPark.ContactDetails.FaxNumber',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.Annotation',
               'StationList.Station.StationFacilities.WebKiosk.Open.Annotation']
FLAT_DATA = ['StationList.Station.ChangeHistory.ChangedBy', 'StationList.Station.ChangeHistory.LastChangedDate',
               'StationList.Station.CrsCode', 'StationList.Station.AlternativeIdentifiers.NationalLocationCode',
               'StationList.Station.Name', 'StationList.Station.SixteenCharacterName',
               'StationList.Station.Address.PostalAddress.A_5LineAddress.Line',
               'StationList.Station.Address.PostalAddress.A_5LineAddress.PostCode', 'StationList.Station.Longitude',
               'StationList.Station.Latitude', 'StationList.Station.StationOperator',
               'StationList.Station.Staffing.StaffingLevel',
               'StationList.Station.Staffing.ClosedCircuitTelevision.Available',
               'StationList.Station.InformationSystems.InformationAvailableFromStaff',
               'StationList.Station.InformationSystems.InformationServicesOpen.Annotation.Note',
               'StationList.Station.InformationSystems.CIS',
               'StationList.Station.InformationSystems.CustomerHelpPoints.Available',
               'StationList.Station.Fares.TicketOffice.Available', 'StationList.Station.Fares.TicketMachine.Available',
               'StationList.Station.Fares.OystercardIssued', 'StationList.Station.Fares.UseOystercard',
               'StationList.Station.Fares.AlwaysShowOysterCardFields', 'StationList.Station.Fares.SmartcardIssued',
               'StationList.Station.Fares.SmartcardValidator', 'StationList.Station.Fares.SmartcardComments.Note',
               'StationList.Station.Fares.PenaltyFares.Url',
               'StationList.Station.PassengerServices.CustomerService.Annotation.Note',
               'StationList.Station.PassengerServices.LeftLuggage.ContactDetails.Url',
               'StationList.Station.PassengerServices.LeftLuggage.Available',
               'StationList.Station.PassengerServices.LostProperty.ContactDetails.PrimaryTelephoneNumber.TelNationalNumber',
               'StationList.Station.PassengerServices.LostProperty.ContactDetails.Url',
               'StationList.Station.PassengerServices.LostProperty.Available',
               'StationList.Station.PassengerServices.LostProperty.OperatorName',
               'StationList.Station.StationFacilities.FirstClassLounge.Available',
               'StationList.Station.StationFacilities.SeatedArea.Available',
               'StationList.Station.StationFacilities.WaitingRoom.Available',
               'StationList.Station.StationFacilities.Trolleys.Available',
               'StationList.Station.StationFacilities.StationBuffet.Available',
               'StationList.Station.StationFacilities.Toilets.Available',
               'StationList.Station.StationFacilities.BabyChange.Available',
               'StationList.Station.StationFacilities.Showers.Available',
               'StationList.Station.StationFacilities.Telephones.Exists',
               'StationList.Station.StationFacilities.Telephones.UsageType',
               'StationList.Station.StationFacilities.WiFi.Annotation.Note',
               'StationList.Station.StationFacilities.WiFi.Available',
               'StationList.Station.StationFacilities.WebKiosk.Available',
               'StationList.Station.StationFacilities.PostBox.Available',
               'StationList.Station.StationFacilities.TouristInformation.Available',
               'StationList.Station.StationFacilities.AtmMachine.Available',
               'StationList.Station.StationFacilities.BureauDeChange.Available',
               'StationList.Station.StationFacilities.Shops.Available',
               'StationList.Station.Accessibility.Helpline.ContactDetails.Annotation.Note',
               'StationList.Station.Accessibility.Helpline.ContactDetails.Url',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.Accessibility.StaffHelpAvailable.Annotation.Note',
               'StationList.Station.Accessibility.StaffHelpAvailable.Available',
               'StationList.Station.Accessibility.InductionLoop',
               'StationList.Station.Accessibility.AccessibleTicketMachines.Annotation.Note',
               'StationList.Station.Accessibility.AccessibleTicketMachines.Available',
               'StationList.Station.Accessibility.HeightAdjustedTicketOfficeCounter.Available',
               'StationList.Station.Accessibility.RampForTrainAccess.Available',
               'StationList.Station.Accessibility.NearestStationsWithMoreFacilities.CrsCode',
               'StationList.Station.Accessibility.NationalKeyToilets.Available',
               'StationList.Station.Accessibility.StepFreeAccess.Annotation.Note',
               'StationList.Station.Accessibility.StepFreeAccess.Coverage',
               'StationList.Station.Accessibility.ImpairedMobilitySetDown.Available',
               'StationList.Station.Accessibility.WheelchairsAvailable.Available',
               'StationList.Station.Interchange.CycleStorage.Spaces',
               'StationList.Station.Interchange.CycleStorage.Sheltered',
               'StationList.Station.Interchange.CycleStorage.Cctv',
               'StationList.Station.Interchange.CarPark.ContactDetails.PostalAddress.Line',
               'StationList.Station.Interchange.CarPark.ContactDetails.Url',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.Interchange.CarPark.OperatorName', 'StationList.Station.Interchange.CarPark.Name',
               'StationList.Station.Interchange.CarPark.Spaces', 'StationList.Station.Interchange.CarPark.Charges.Free',
               'StationList.Station.Interchange.CarPark.NumberAccessibleSpaces',
               'StationList.Station.Interchange.CarPark.AccessibleCarParkEquipment',
               'StationList.Station.Interchange.CarPark.Cctv',
               'StationList.Station.Interchange.RailReplacementServices.Annotation.Note',
               'StationList.Station.Interchange.TaxiRank.Annotation.Note',
               'StationList.Station.StationAlerts.AlertText', 'StationList.Station.TrainOperatingCompanies.TocRef',
               'StationList.Station.Fares.PrepurchaseCollection.TicketMachine',
               'StationList.Station.Interchange.CarPark.ContactDetails.PrimaryTelephoneNumber.TelNationalNumber',
               'StationList.Station.Fares.TicketOffice.Open.Annotation.Note',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.Fares.PrepurchaseCollection.TicketOffice',
               'StationList.Station.Fares.SmartcardTopup.TicketOffice',
               'StationList.Station.Fares.SmartcardTopup.TicketMachine',
               'StationList.Station.Interchange.CarPark.ContactDetails.Annotation.Note',
               'StationList.Station.Interchange.CarPark.AccessibleCarParkEquipmentNote',
               'StationList.Station.Interchange.OnwardTravel.Annotation.Note',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.Unavailable',
               'StationList.Station.Interchange.CycleStorage.Location.Note',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.Fares.TicketOffice.Location.Note',
               'StationList.Station.StationFacilities.WaitingRoom.Open.Annotation.Note',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.StationFacilities.StationBuffet.Annotation.Note',
               'StationList.Station.StationFacilities.Toilets.Location.Note',
               'StationList.Station.Accessibility.Helpline.Annotation.Note',
               'StationList.Station.Accessibility.AccessibleTaxis.Annotation.Note',
               'StationList.Station.Accessibility.AccessiblePublicTelephones.Annotation.Note',
               'StationList.Station.Accessibility.ImpairedMobilitySetDown.Annotation.Note',
               'StationList.Station.Interchange.CycleStorage.Type',
               'StationList.Station.Interchange.CarPark.ContactDetails.EmailAddress',
               'StationList.Station.Interchange.CarPark.Charges.Off-peak',
               'StationList.Station.Interchange.CarPark.Charges.PerHour',
               'StationList.Station.Interchange.CarPark.Charges.Daily',
               'StationList.Station.Interchange.CarPark.Charges.Weekly',
               'StationList.Station.Interchange.CarPark.Charges.Monthly',
               'StationList.Station.Interchange.CarPark.Charges.ThreeMonthly',
               'StationList.Station.Interchange.CarPark.Charges.SixMonthly',
               'StationList.Station.Interchange.CarPark.Charges.Annual',
               'StationList.Station.Interchange.CarPark.Charges.Saturday',
               'StationList.Station.Interchange.CarPark.Charges.Sunday',
               'StationList.Station.Interchange.CarPark.Charges.Note',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.Unavailable',
               'StationList.Station.Accessibility.NationalKeyToilets.Location.Note',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.InformationSystems.CustomerHelpPoints.Annotation.Note',
               'StationList.Station.StationFacilities.PostBox.Location.Note',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.StationFacilities.Shops.Annotation.Note',
               'StationList.Station.Interchange.CycleHire.Annotation.Note',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.Accessibility.TicketGates.Available',
               'StationList.Station.Interchange.CycleStorage.Annotation.Note',
               'StationList.Station.StationFacilities.FirstClassLounge.Annotation.Note',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.OpeningHours.Unavailable',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.StationFacilities.WaitingRoom.Location.Note',
               'StationList.Station.StationFacilities.AtmMachine.Location.Note',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.Accessibility.TicketGates.Annotation.Note',
               'StationList.Station.Interchange.Airport.Annotation.Note',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.TwentyFourHours',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours',
               'StationList.Station.PassengerServices.LeftLuggage.OperatorName',
               'StationList.Station.Accessibility.NearestStationsWithMoreFacilities.Annotation.Note',
               'StationList.Station.Interchange.CarPark.ContactDetails.PostalAddress.PostCode',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.Unavailable',
               'StationList.Station.Interchange.Port.Annotation.Note',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.Unavailable',
               'StationList.Station.Fares.PenaltyFares.TrainOperator',
               'StationList.Station.Accessibility.HeightAdjustedTicketOfficeCounter.Annotation.Note',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.Interchange.CarPark.AccessibleSpacesNote',
               'StationList.Station.Fares.OystercardTopup.TicketMachine',
               'StationList.Station.Fares.Travelcard.TravelcardZone',
               'StationList.Station.PassengerServices.LostProperty.Open.Annotation.Note',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.Interchange.MetroServices.Annotation.Note',
               'StationList.Station.Fares.OysterComments.Note',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.StationFacilities.BabyChange.Location.Note',
               'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.Fares.OystercardTopup.TicketOffice',
               'StationList.Station.StationFacilities.SeatedArea.Annotation.Note',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.StartTime',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.OpeningHours.OpenPeriod.EndTime',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.StationFacilities.TouristInformation.Location.Note',
               'StationList.Station.StationCategory',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Saturday',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Sunday',
               'StationList.Station.Interchange.CarPark.Annotation.Note',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.Interchange.CarHire.Annotation.Note',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.Interchange.CarPark.ContactDetails.AlternatePublicTelephoneNumbers.TelephoneNumber.TelNationalNumber',
               'StationList.Station.Accessibility.Helpline.Open.Annotation.Note',
               'StationList.Station.PassengerServices.LeftLuggage.ContactDetails.PrimaryTelephoneNumber.TelNationalNumber',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.Interchange.CarPark.ContactDetails.FaxNumber.TelNationalNumber',
               'StationList.Station.Interchange.RailReplacementServices.RailReplacementMap',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Weekend',
               'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours.Unavailable',
               'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.OpeningHours.Unavailable',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.MondayToSunday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.MondayToFriday',
               'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Monday',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Tuesday',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Wednesday',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Thursday',
               'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Friday',
               'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.AllBankHolidays',
               'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays',
               'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays',
               'StationList.Station.StationFacilities.FirstClassLounge.Open.Annotation.Note',
               'StationList.Station.StationFacilities.WebKiosk.Open.Annotation.Note']
DATA_TYPES = {'StationList.Station.Longitude': float, 'StationList.Station.Latitude': float,
            'StationList.Station.Staffing.ClosedCircuitTelevision.Available': bool,
            'StationList.Station.InformationSystems.CustomerHelpPoints.Available': bool,
            'StationList.Station.Fares.TicketOffice.Available': bool,
            'StationList.Station.Fares.TicketMachine.Available': bool,
            'StationList.Station.Fares.OystercardIssued': bool, 'StationList.Station.Fares.UseOystercard': bool,
            'StationList.Station.Fares.AlwaysShowOysterCardFields': bool,
            'StationList.Station.Fares.SmartcardIssued': bool, 'StationList.Station.Fares.SmartcardValidator': bool,
            'StationList.Station.PassengerServices.LeftLuggage.Available': bool,
            'StationList.Station.PassengerServices.LostProperty.Available': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Available': bool,
            'StationList.Station.StationFacilities.SeatedArea.Available': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Available': bool,
            'StationList.Station.StationFacilities.Trolleys.Available': bool,
            'StationList.Station.StationFacilities.StationBuffet.Available': bool,
            'StationList.Station.StationFacilities.Toilets.Available': bool,
            'StationList.Station.StationFacilities.BabyChange.Available': bool,
            'StationList.Station.StationFacilities.Showers.Available': bool,
            'StationList.Station.StationFacilities.Telephones.Exists': bool,
            'StationList.Station.StationFacilities.WiFi.Available': bool,
            'StationList.Station.StationFacilities.WebKiosk.Available': bool,
            'StationList.Station.StationFacilities.PostBox.Available': bool,
            'StationList.Station.StationFacilities.TouristInformation.Available': bool,
            'StationList.Station.StationFacilities.AtmMachine.Available': bool,
            'StationList.Station.StationFacilities.BureauDeChange.Available': bool,
            'StationList.Station.StationFacilities.Shops.Available': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Available': bool,
            'StationList.Station.Accessibility.InductionLoop': bool,
            'StationList.Station.Accessibility.AccessibleTicketMachines.Available': bool,
            'StationList.Station.Accessibility.HeightAdjustedTicketOfficeCounter.Available': bool,
            'StationList.Station.Accessibility.RampForTrainAccess.Available': bool,
            'StationList.Station.Accessibility.NationalKeyToilets.Available': bool,
            'StationList.Station.Accessibility.ImpairedMobilitySetDown.Available': bool,
            'StationList.Station.Accessibility.WheelchairsAvailable.Available': bool,
            'StationList.Station.Interchange.CycleStorage.Spaces': int,
            'StationList.Station.Interchange.CycleStorage.Cctv': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.Interchange.CarPark.Spaces': int,
            'StationList.Station.Interchange.CarPark.Charges.Free': bool,
            'StationList.Station.Interchange.CarPark.NumberAccessibleSpaces': int,
            'StationList.Station.Interchange.CarPark.AccessibleCarParkEquipment': bool,
            'StationList.Station.Interchange.CarPark.Cctv': bool,
            'StationList.Station.Fares.PrepurchaseCollection.TicketMachine': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.Fares.PrepurchaseCollection.TicketOffice': bool,
            'StationList.Station.Fares.SmartcardTopup.TicketOffice': bool,
            'StationList.Station.Fares.SmartcardTopup.TicketMachine': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.Unavailable': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.Unavailable': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.Accessibility.TicketGates.Available': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.OpeningHours.Unavailable': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.OpeningHours.TwentyFourHours': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.Unavailable': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.OpeningHours.Unavailable': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.Fares.OystercardTopup.TicketMachine': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.StationFacilities.WaitingRoom.Open.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.Fares.OystercardTopup.TicketOffice': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Saturday': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Sunday': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.DayTypes.Weekend': bool,
            'StationList.Station.Interchange.CarPark.Open.DayAndTimeAvailability.OpeningHours.Unavailable': bool,
            'StationList.Station.PassengerServices.LostProperty.Open.DayAndTimeAvailability.OpeningHours.Unavailable': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.MondayToSunday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.DayTypes.MondayToFriday': bool,
            'StationList.Station.StationFacilities.WebKiosk.Open.DayAndTimeAvailability.OpeningHours.TwentyFourHours': bool,
            'StationList.Station.StationFacilities.FirstClassLounge.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Monday': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Tuesday': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Wednesday': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Thursday': bool,
            'StationList.Station.Accessibility.Helpline.Open.DayAndTimeAvailability.DayTypes.Friday': bool,
            'StationList.Station.InformationSystems.InformationServicesOpen.DayAndTimeAvailability.DayTypes.AllBankHolidays': bool,
            'StationList.Station.Fares.TicketOffice.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays': bool,
            'StationList.Station.Accessibility.StaffHelpAvailable.Open.DayAndTimeAvailability.DayTypes.AllBankHolidays': bool}
